#!/bin/bash
UNIX=("Debain " "Red hat " "Ubuntu " "Suse " "Fedora")
echo Showing whole array: ${UNIX[@]}
echo Size of array: ${#UNIX[*]}
echo Length of element on 2nd index: echo ${#UNIX[2]}
echo Extracting 2 elements from position 3: ${UNIX[@]:2:2} 
echo search and replace: ${UNIX[@]/Ubuntu/SCO}
UNIX=(${UNIX[@]} "AIX" "HP-UX")
unset UNIX[2]
echo Showing whole array UNIX: ${UNIX[@]}
LINUX=( ${UNIX[@]} )
BASH=( ${LINUX[@]} ${UNIX[@]} )
echo Showing whole array BASH: ${BASH[@]}
unset UNIX
unset LINUX


